### ISSUE TITLE
SA MARCHE PAS

### ISSUE THREAD

**Issue by bycop** [AzodFR/Philosophers#1]

**Comment by AzodFR** [comment]
dis m'en plus

**Comment by bycop** [comment]
C'est pas ici le guide  "Comment finir cub3D en 2 étapes grâce à MA technique ?" J'ai payé 50e la formation quand même MONSIEUR

**Comment by AzodFR** [comment]
je suis désolé mais je vend la formation 200€, tu t'es fais arnaquer

**Comment by bycop** [comment]
rend mon quad

**Comment by AzodFR** [comment]
bonsoir non
